# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:C8Q6cHJwNP+2lsSHSCACVa0YLkhU4tzz4n7+KgAigPdct8gGXBmyUCoM0GuHeYpCRlGDaKdcY5xs/HmKOBraxgoztoZ9o970w3zW938sowXUHh85zQWD5OTFkm5kyX+H6OpLeviH+GfxCRykuTEyy1hd3cH4Jiu9TNXkQ68a0D2hxkvBIMzrDtDIPqaluEhC6fV5Jo6VgWOggfHcHu9qNe5RGfRIiuA6OLHIJkqlTtjbV2L8,iv:fDrqW4mxtA5WnWML9ilvXpHSDaQARpBAOvSV5LOr4I8=,tag:F6EBc55CQt9/yW4zp2JEAQ==,type:str]
sops:
  age:
    - recipient: age1u3vaz5emmapah38cuwsqdwkus55edvgs648naea0mylmeq0nl9espv3960
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2FJTm4rM0tnWWxFNUxk
        RHJxUWxac2tNZ1Q4TGJnbXFvbHN3L2diWUFBCm1RekwvRThpRy9lQXhEblN5WWkv
        TkRyVDk3S2lSNnJueXpLaXRxckt4V0kKLS0tIGxVQUNkQjVkMldRTzVzSWlZdU9o
        MC9XYmdlT0Z4VXpwWmN6ZHNuQUFuQjQKRjkvjy0HCJqFAKqsUWSiC94H5y9vNItW
        ISq5zQ4LD9sy2cYluDNkfG2TH7aW74aBmjJOevYXs/UfWfg7zaEykQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T22:11:05Z"
  mac: ENC[AES256_GCM,data:WX9L34FPgZFfU4H+QX24+yiZHij28/Fb+Yab/VnNWrKc6m/vdmEj71UEyWVddrH6iRgPx4k81B1rijfURDVjxnMprE6BT2W+i+GjHuijP5nMSKMCy3OonIaCvzCN8YJ6VuYGkdbDqX1Z2MJSG9FCVKjYp5NfCX7WZLoHmd8ACpc=,iv:Dkxtn+58CjaHxEviauD6MHYsVcs3SAYMHhGhMzX+wOI=,tag:d0zkGUF7Daju/EkLTKppAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
