# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:z9ACrtEF7YnkhaULp7/6PnS5XNzOkSpgdq35bvWGXmFjnPeIAS5IEA==,iv:PMZmNJodM5qmXXoX1+4TS+Qq7RcO03Th4auahNg55Ig=,tag:6i4ghHGdqPfrxvjwQhsh3Q==,type:str]
sops:
  age:
    - recipient: age1u3vaz5emmapah38cuwsqdwkus55edvgs648naea0mylmeq0nl9espv3960
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2pkT1BrbHA4aWZiOXVt
        M2Yya2xHVzlrMVRRTTl5VHJGdjMvTUlNc0NBCmNMbnlvQVAvY3BDb0lkcDNyYW50
        bHV0elk0SExvWWZBZUtTSlVvSFp2dXMKLS0tICtHMjFnT1Q0dWZvMnpYalF4MDRL
        LzljYnVVTDh4SnVCcHBWa0hRUmhtZEEKWd2UWsAOlqGRGW28n/EkZoYrQwdoGJOt
        kFSv8bF4f5LvgMepsJd59KXFLjhURFQoMeCwT0xPSDAwRXIAYs2MZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T22:05:08Z"
  mac: ENC[AES256_GCM,data:HtKBEcpSOKUl4M9DDoHef1vugQ0l8IqIOCXM4bXY7knp1lWl2Ij/QiEIFwP4jWpyDJhmpIMPudlGepY9pYHyvGj6jprm5p/f7sZV03RwxZL3KoJnB98xuSCCJzIuNNlwqnmHVJimRhs6koodoM5+mgxRYrk6MtSFju/OpUwzZD4=,iv:HKvGuMGrjnB74zjVN2zN1GjTtdg+gct0iDVTmdX527M=,tag:BSJZwJBRQD1dyHghYy2RTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
